export function SvgGlobalDefs() {
	return (
		<svg style={{ width: 0, height: 0, opacity: 0, position: 'absolute' }}>
			<defs>
				<filter
					id='standard-logo-box-shadow'
					x='0'
					y='-5'
					width='150'
					height='58'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feColorMatrix
						in='SourceAlpha'
						type='matrix'
						values='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0'
						result='hardAlpha'
					/>
					<feOffset
						dx='-2'
						dy='-2'
					/>
					<feGaussianBlur stdDeviation='7.5' />
					<feComposite
						in2='hardAlpha'
						operator='out'
					/>
					<feColorMatrix
						type='matrix'
						values='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0'
					/>
					<feBlend
						mode='normal'
						in2='BackgroundImageFix'
						result='effect1_dropShadow_1_84'
					/>
					<feColorMatrix
						in='SourceAlpha'
						type='matrix'
						values='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0'
						result='hardAlpha'
					/>
					<feOffset
						dx='2'
						dy='2'
					/>
					<feGaussianBlur stdDeviation='7.5' />
					<feComposite
						in2='hardAlpha'
						operator='out'
					/>
					<feColorMatrix
						type='matrix'
						values='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0'
					/>
					<feBlend
						mode='normal'
						in2='effect1_dropShadow_1_84'
						result='effect2_dropShadow_1_84'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='effect2_dropShadow_1_84'
						result='shape'
					/>
				</filter>
				<filter
					id='logo-footer-blur'
					x='-43.7836'
					y='0.389893'
					width='341.783'
					height='184.818'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='BackgroundImageFix'
						result='shape'
					/>
					<feGaussianBlur
						stdDeviation='4'
						result='effect1_foregroundBlur_1_104'
					/>
				</filter>
				<filter
					id='section-logo-offer-blur'
					x='0.446747'
					y='0.0722656'
					width='383.45'
					height='206.41'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='BackgroundImageFix'
						result='shape'
					/>
					<feGaussianBlur
						stdDeviation='4'
						result='effect1_foregroundBlur_1_272'
					/>
				</filter>
				<filter
					id='section-logo-news-blur'
					x='0.000946045'
					y='0.289856'
					width='341.783'
					height='184.818'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='BackgroundImageFix'
						result='shape'
					/>
					<feGaussianBlur
						stdDeviation='4'
						result='effect1_foregroundBlur_1_302'
					/>
				</filter>
				<filter
					id='section-logo-schedule-blur'
					x='0.00758266'
					y='0.931167'
					width='315.259'
					height='209.259'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='BackgroundImageFix'
						result='shape'
					/>
					<feGaussianBlur
						stdDeviation='6.06469'
						result='effect1_foregroundBlur_1_747'
					/>
				</filter>
				<filter
					id='section-logo-prices-blur'
					x='0.5'
					y='0.374023'
					width='383.45'
					height='206.41'
					filterUnits='userSpaceOnUse'
					colorInterpolationFilters='sRGB'
				>
					<feFlood
						floodOpacity='0'
						result='BackgroundImageFix'
					/>
					<feBlend
						mode='normal'
						in='SourceGraphic'
						in2='BackgroundImageFix'
						result='shape'
					/>
					<feGaussianBlur
						stdDeviation='4'
						result='effect1_foregroundBlur_14_1102'
					/>
				</filter>
			</defs>
		</svg>
	)
}
